sonar.projectKey=ssd-practice
sonar.projectName=SSD Practice
sonar.projectVersion=1.0

sonar.sources=web
sonar.tests=web
sonar.test.inclusions=web/test_*.py
sonar.exclusions=web/test_*.py,web/node_modules/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8